# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lanshare < Formula
  desc "Share files instantly over your local network with QR codes"
  homepage "https://github.com/sebaswvv/lan-share"
  version "0.0.7-beta"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebaswvv/lan-share/releases/download/v0.0.7-beta/lan-share_0.0.7-beta_darwin_amd64.tar.gz"
      sha256 "e0f0fc4c3384e42f4ae3880b85d38751397c164cb62d37008e44062cad007786"

      def install
        bin.install "lanshare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebaswvv/lan-share/releases/download/v0.0.7-beta/lan-share_0.0.7-beta_darwin_arm64.tar.gz"
      sha256 "eb5986646fa1378613b8c5fa4e094c40eb6af74767b6572c5c7157edc58e7e9e"

      def install
        bin.install "lanshare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebaswvv/lan-share/releases/download/v0.0.7-beta/lan-share_0.0.7-beta_linux_amd64.tar.gz"
      sha256 "38862a46b01bac7fe26d835b50aab557c447f9fd427518ad93e212c3c3f80260"
      def install
        bin.install "lanshare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebaswvv/lan-share/releases/download/v0.0.7-beta/lan-share_0.0.7-beta_linux_arm64.tar.gz"
      sha256 "6195b6cad38bbe61c3b6f519ff4fe16896765f30b4528274ab9059e0c9e53892"
      def install
        bin.install "lanshare"
      end
    end
  end
end
