# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lanshare < Formula
  desc "Share files instantly over your local network with QR codes"
  homepage "https://github.com/sebaswvv/lan-share"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sebaswvv/lan-share/releases/download/v1.0.2/lan-share_1.0.2_darwin_amd64.tar.gz"
      sha256 "148b5d06003e533507d7facf601447297b073d4c6a963dc2cc308004729dd5f9"

      def install
        bin.install "lanshare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sebaswvv/lan-share/releases/download/v1.0.2/lan-share_1.0.2_darwin_arm64.tar.gz"
      sha256 "c371158b5346c87bb50c4fa154ef8a441ff45083e888decb04ffe3f95afc086a"

      def install
        bin.install "lanshare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebaswvv/lan-share/releases/download/v1.0.2/lan-share_1.0.2_linux_amd64.tar.gz"
      sha256 "e9991d0a1df60d858d6b1a0b2b88cf025a8c3151c13631fb9110c46d409d9792"
      def install
        bin.install "lanshare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sebaswvv/lan-share/releases/download/v1.0.2/lan-share_1.0.2_linux_arm64.tar.gz"
      sha256 "e3cd9d2e84209fff7505b92f0fee787ed9549163dac608a48218de0952ad4737"
      def install
        bin.install "lanshare"
      end
    end
  end
end
